In [118]:
import numpy as np

In [119]:
np.__version__

'1.21.5'

In [120]:
a = np.array([1,2,3,4,5])

In [121]:
print(a)

[1 2 3 4 5]


In [122]:
print(a.dtype)

int32


In [123]:
print(a.shape)

(5,)


In [124]:
print(a.ndim)

1


In [125]:
print(a.size)

5


In [126]:
print(a.itemsize)

4


In [127]:
a[0]

1

In [128]:
a[0]=6

In [129]:
a[0]

6

In [130]:
b = np.array([3,4,5,6,4])

In [131]:
c = a*b

In [132]:
print(c)

[18  8 15 24 20]


In [133]:
print(c.sum())

85


In [134]:
#diff between array and list

In [135]:
l =[1,2,3]

In [136]:
r = np.array([2,5,6])

In [137]:
print(l)
print(r)

[1, 2, 3]
[2 5 6]


In [138]:
2*l

[1, 2, 3, 1, 2, 3]

In [139]:
2*r

array([ 4, 10, 12])

In [140]:
#dot product

In [141]:
da = np.array([1,2])
db = np.array([3,4])

In [142]:
dot = 0
for i in range(len(da)):
    dot += da[i] * db[i]
    print(dot)

3
11


In [143]:
#using numpy dot

In [144]:
dot = np.dot(da,db)

In [145]:
print(dot)

11


In [146]:
#newer version of dot 

In [147]:
da.dot(db)

11

In [148]:
#newer version

In [149]:
da@db

11

In [150]:
#speed Test of numpy array and list

In [151]:
from timeit import default_timer as timer

In [152]:
a = np.random.randn(1000)

In [153]:
b = np.random.randn(1000)

In [154]:
A = list(a)

In [155]:
B = list(b)

In [156]:
T = 100

In [157]:
def dot1():
    dot = 0
    for i in range(len(A)):
    dot += A[i]*B[i]
    return dot


IndentationError: expected an indented block (2037896248.py, line 4)

In [158]:
def dot2():
    return np.dot(a,b)

In [159]:
#multi dimensional array 

In [160]:
a = np.array([[1,2],[3,4]])

In [161]:
a

array([[1, 2],
       [3, 4]])

In [162]:
a.shape

(2, 2)

In [163]:
#access elements
#row first, then column

In [164]:
print(a[0])

[1 2]


In [165]:
print(a[0][0])

1


In [166]:
print(a[:,0])

[1 3]


In [167]:
print(a[0,0])

1


In [168]:
print(a[0,: ])

[1 2]


In [169]:
#transpose

In [170]:
print(a,T)

[[1 2]
 [3 4]] 100


In [171]:
print(T,a)

100 [[1 2]
 [3 4]]


In [172]:
#matrix multiplication

In [173]:
d =  np.array([[3,4],[5,6]])

In [174]:
u = a@d

In [175]:
print(u)

[[13 16]
 [29 36]]


In [176]:
z = a.dot(d)

In [177]:
print(z)

[[13 16]
 [29 36]]


In [178]:
print(a*d)

[[ 3  8]
 [15 24]]


In [179]:
b = np.array([[1,2,3],[4,5,4]])

In [180]:
f = a.dot(b)

In [181]:
print(f)

[[ 9 12 11]
 [19 26 25]]


In [182]:
#determinants

In [183]:
lst = [1,2,4,5]

In [184]:
lst.sort()

In [185]:
lst[len(lst)//2]

4

In [186]:
lst[-2]

4

In [187]:
lst[1] = 19

In [188]:
lst

[1, 19, 4, 5]

In [189]:
det = np.linalg.det(a)

In [190]:
print(det)

-2.0000000000000004


In [191]:
#inverse of a matrix

In [192]:
inv = np.linalg.inv(a)

In [193]:
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [194]:
#diag of a matrix

In [195]:
dia = np.diag(a)

In [196]:
print(dia)

[1 4]


In [197]:
#diag on a vector returns diagonal matrix (overloaded functio)

In [198]:
c = np.diag([1,4])

In [199]:
print(c)

[[1 0]
 [0 4]]


In [200]:
#indexing , slicing and boolen indexing

In [201]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [202]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [203]:
#integer array indexing 

In [204]:
b= a[0,1]

In [205]:
print(b)

2


In [206]:
print(a[2])

[ 9 10 11 12]


In [207]:
#slicing

In [208]:
print(a[:,1]) #row

[ 2  6 10]


In [209]:
print(a[2,:]) #column

[ 9 10 11 12]


In [210]:
print(a[0:2,2:3])

[[3]
 [7]]


In [211]:
#indexing starting from the end

In [212]:
print(a[-1,-1])

12


In [213]:
#boolean indesing

In [214]:
j = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [215]:
print(j)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [216]:
bool_indx = j>2

In [217]:
bool_indx

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [218]:
print(a[bool_indx])

[ 3  4  5  6  7  8  9 10 11 12]


In [219]:
print(a[a>2])

[ 3  4  5  6  7  8  9 10 11 12]


In [220]:
#numpy.where

In [221]:
u = np.where(a>2,a,'fool')

In [222]:
print(u)

[['fool' 'fool' '3' '4']
 ['5' '6' '7' '8']
 ['9' '10' '11' '12']]


In [223]:
#fancy indexing: access multiple indices at once

In [224]:
a = np.array([10,19,30,41,50,61])

In [225]:
b= a[[1,3,5]] #prints the element in 1,3,5

In [226]:
print(b)

[19 41 61]


In [229]:
even = np.argwhere(a%2==0).flatten()

In [230]:
print(even)

[0 2 4]


In [231]:
a_even = a[even]

In [234]:
print(a_even)

[10 30 50]


In [235]:
#Reshaping :creating the matrix you want 

In [258]:
a = np.arange(1,7
             )

In [259]:
print(a)

[1 2 3 4 5 6]


In [260]:
b = a.reshape(2,3) #error occurs if shape cannot be used 

In [261]:
print(b)

[[1 2 3]
 [4 5 6]]


In [262]:
c = a.reshape(3,2) #getting 3 by 2 matrix 

In [263]:
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [264]:
#new axis is used to create a new axis in the data 
#needed when  a model require the data to be shaped in a certain manner 

In [265]:
print(a)

[1 2 3 4 5 6]


In [266]:
print(a.shape)

(6,)


In [267]:
d = a[np.newaxis, :]

In [268]:
print(d)

[[1 2 3 4 5 6]]


In [269]:
print(d.shape)

(1, 6)


In [271]:
d = a[:, np.newaxis]

In [272]:
print(d)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [273]:
print(d.shape)

(6, 1)


In [ ]:
#conctenation  :

In [288]:
a = np.array([[1,2],[3,4]])

In [289]:
b = np.array([[5,6]])

In [290]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [291]:
#combine a and b

In [292]:
c = np.concatenate((a,b), axis=None)

In [293]:
print(c)

[1 2 3 4 5 6]


In [294]:
c = np.concatenate((a,b))

In [296]:
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [298]:
c = np.concatenate((a,b.T), axis=1)

In [299]:
print(c)

[[1 2 5]
 [3 4 6]]


In [ ]:
#hstack: stack arrays in sequence horizontally (column wise). needs a tuple

In [300]:
a = np.array([1,2,3,4])

In [301]:
b = np.array([5,6,7,8])

In [302]:
c = np.hstack((a,b))

In [304]:
print(c)

[1 2 3 4 5 6 7 8]


In [310]:
a = np.array([[1,2],[3,4]])

In [311]:
b = np.array([[5,6],[7,8]])

In [312]:
c = np.hstack((a,b))

In [313]:
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#vstack stack arrays in seqence vertically (row wise). neeeds a tuple

In [314]:
a = np.array([1,2,3,4])

In [315]:
b = np.array([5,6,7,8])

In [317]:
c = np.vstack((a,b))

In [318]:
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [319]:
a = np.array([[1,2],[3,4]])

In [320]:
b = np.array([[5,6],[7,8]])

In [321]:
c = np.vstack((a,b))

In [322]:
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#broadcasting: the ability of NumPy to treat arrays of different shapes during arithmetic operations.

In [326]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [327]:
b = np.array([1,0,1])

In [328]:
print(a+b) #1+1= 2, 0+2=2,3+1=4

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
#functions and axis :  

In [330]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])

In [331]:
print(a.sum())

210


In [332]:
print(a.sum(axis=None))

210


In [333]:
print(a.sum(axis = 0))

[24 26 28 30 32 34 36]


In [334]:
print(a.sum(axis = 1))

[ 70 140]


In [ ]:
#datatypes:  Yes, a numpy array can store different data String, Integer, Complex, Float, Boolean

In [336]:
x = np.array([1,2])

In [337]:
print(x.dtype)

int32


In [338]:
x = np.array([1.0,2.0])

In [339]:
print(x.dtype)

float64


In [ ]:
#force a particular daTATYPE HOW MANY BTS (HOW PRECISE)

In [340]:
x = np.array([1,2], dtype=np.int64) #8 bytes

In [341]:
print(x.dtype)

int64


In [346]:
x = np.array([1,2], dtype=np.float32) #8 bytes

In [347]:
print(x.dtype)

float32


In [ ]:
#copying : Return an array copy of the given object.

In [349]:
x = np.array([1,2,3])

In [350]:
y =x #only copies reference

In [351]:
y[0]

1

In [352]:
x

array([1, 2, 3])

In [353]:
y

array([1, 2, 3])

In [354]:
a = np.array([1,2,3])

In [355]:
b = a.copy()  #actual copy

In [356]:
b[0]

1

In [357]:
print(a)

[1 2 3]


In [358]:
print(b)

[1 2 3]


In [ ]:
#generating arrays

In [ ]:
#ones

In [359]:
a = np.ones((2,3))

In [361]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [362]:
a = np.zeros((2,3))

In [363]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#specific values

In [366]:
c = np.full((3,3),5)

In [378]:
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [379]:
#identity

In [387]:
d = np.eye(4) #4*4 matrix [1,0,0,0]

In [388]:
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [382]:
#arrange

In [383]:
e = np.arange(10)

In [384]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace  :  It is used to create an evenly spaced sequence in a specified interval.

In [389]:
f = np.linspace(0,10,5)

In [390]:
print(f)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#random numbers

In [392]:
a = np.random.random((3,2)) #uniform 0-1 distribution  needs tuple 

In [393]:
print(a)

[[0.24250841 0.02816658]
 [0.22363561 0.41247183]
 [0.05702312 0.14475645]]


In [395]:
a = np.random.randn(3,2)  #normal/Gussian distribution, mean 0 and no tuple

In [396]:
a

array([[-1.34725753,  0.46898553],
       [ 0.55499728, -0.12186293],
       [ 1.38065866,  1.63143138]])

In [401]:
c = np.random.random(1000)

In [402]:
c

array([1.03388003e-02, 6.41927964e-01, 9.86838073e-01, 6.72358866e-01,
       6.41481514e-01, 2.53098283e-01, 3.66057279e-01, 5.74893339e-01,
       5.08682258e-01, 8.83905954e-01, 8.66731048e-01, 8.13226498e-01,
       9.57168993e-01, 8.03433333e-01, 6.41782976e-01, 7.91567294e-01,
       7.74010964e-01, 4.07955254e-01, 8.98578332e-01, 7.32400432e-01,
       2.21037686e-01, 5.38395308e-01, 9.97699827e-01, 3.26378517e-01,
       7.04755267e-01, 5.26906003e-01, 4.20050516e-01, 6.99725508e-01,
       9.03122526e-01, 8.73649956e-01, 5.86382056e-01, 8.78506553e-01,
       8.97157573e-01, 7.05266114e-01, 5.81867870e-01, 7.12587006e-01,
       5.68877140e-01, 7.26022018e-01, 3.29294872e-01, 9.45695445e-01,
       5.21692415e-01, 7.41621199e-01, 6.72253751e-02, 6.38821634e-02,
       5.28186183e-01, 1.55995964e-01, 1.91945379e-01, 9.07939612e-01,
       6.48479435e-01, 4.16068771e-01, 1.94868423e-01, 7.75471062e-01,
       3.36775307e-01, 1.07267330e-01, 2.75209306e-01, 2.65085351e-01,
      

In [403]:
c.mean(), c.var(), c.std()

(0.4984342083087761, 0.08646721947694556, 0.29405308955517806)

In [404]:
d = np.random.randn(10,3)

In [405]:
d

array([[ 0.24154117,  1.37278012, -1.19458351],
       [ 0.05086119,  0.87440165,  0.4221147 ],
       [-0.92038302, -0.00711832, -1.44176496],
       [ 0.4100729 , -0.76880797,  0.34086545],
       [ 0.93687433,  1.26165355, -1.01837106],
       [ 0.50989129, -0.16227725,  0.10851077],
       [-0.39185773, -0.52037472, -0.77687499],
       [-0.36599851,  2.51307057, -1.14871971],
       [-2.4592337 , -0.36525685,  1.01094102],
       [-0.62785078,  1.17257197,  0.23397171]])

In [406]:
d.mean(), d.var(), d.std()

(-0.023645022355176785, 0.9909476393575617, 0.995463529898289)

In [ ]:
#random integer, low,high,size; high is exclusive

In [407]:
e = np.random.randint(3,10,size=(3,3))  #if we only pas parameter

In [411]:
e

array([[8, 7, 3],
       [9, 4, 6],
       [7, 3, 6]])

In [412]:
#with integer is between 0 up to integer exclusive

In [413]:
f = np.random.choice(7, size=10)

In [414]:
f

array([5, 3, 2, 0, 4, 0, 4, 0, 6, 1])

In [ ]:
#with an array it draws random values from this array

In [417]:
g = np.random.choice([10,22,39,46], size =9)

In [418]:
g

array([22, 10, 10, 22, 10, 39, 22, 10, 22])

In [ ]:
#linear algebra with numpy

In [420]:
a = np.array([[1,2],[3,4]])

In [421]:
eigenvalues, eigenvectors = np.linalg.eig(a)    #eigh if symmetric

In [422]:
print(eigenvalues)
print(eigenvectors)  #column vectors

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [423]:
print(eigenvectors[:,0])

[-0.82456484  0.56576746]


In [ ]:
#solving linear systems with numpy

In [ ]:
#x1+2 x2 =2200
#1.5 x1+4 x2 = 5050

#2 equations and 2 unknown

In [432]:
A = np.array([[1,2],[1.5,4]])
b = np.array([2200,5050])


In [433]:
#BUt: inverse is slow and less accurate

In [434]:
x = np.linalg.inv(A).dot(b)  #not recommended

In [435]:
print(x)

[-1300.  1750.]


In [436]:
#instead use

In [437]:
x = np.linalg.solve(A,b)

In [438]:
print(x)

[-1300.  1750.]


In [ ]:
#load data from csv files
#1) load with np.loadtxt()
#skiprows=1, ...

In [ ]:
data = np.loadtxt('my_file.csv', delimiter=",", dtype=np.float32)

In [ ]:
#2)load with np.genfromtxt
#similar but slight more configuration parameters
#skip_header=0, missing_values="__", filling_values=0.0,...

In [ ]:
data = np.genfromtxt('my_file.csv', delimiter=",",  dtype= np.float32)